#!/usr/bin/env bash
# transfers a file from our client to a server using scp
# Strict host key checking is disabled when using scp

# Check if exactly 4 arguments are passed
if [ "$#" -ne 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Assign arguments to variables for clarity
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

# use scp to transfer file
scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"
