#!/usr/bin/env bash
# Configures Nginx to return a 301 redirect on /redirect_me

apt-get update
apt-get install -y nginx

# Add redirection block
sed -i '/^\s*location \/ {/i \
    location /redirect_me {\n\
        return 301 https://www.youtube.com/;\n\
    }\n' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart

