#!/usr/bin/env bash
# Installs and configures Nginx so that /redirect_me is redirecting to another page.

# exit on any error
set -e

# install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Add redirect in nginx default config
sed -i '/^\s*location \/ {/i \  location /redirect_me {\n	return 301 https://www.youtube.com/;\n  }\n' /etc/nginx/sites-available/default

# restart nginx using service instead of systemctl
sudo service nginx restart
