#!/usr/bin/env bash
# Configures a new Ubuntu machine to serve a custom 404 page with the message: Ceci n'est pas une page

# Update and install nginx
apt-get update
apt-get install -y nginx

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Update Nginx default config
sed -i "/^\s*location \/ {/a \ \n\t# Custom 404 page\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\tinternal;\n\t}" /etc/nginx/sites-available/default

# Restart nginx to apply changes
service nginx restart
